# Generated by Django 5.1.2 on 2024-12-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=30)),
                ('destnation', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
